# Makefile for ly2mei, Andrew Cashner, 2021/11/08
#
# Written in Object Pascal, compiled with Free Pascal Compiler (fpc)
# Documentation generated by PasDoc

app_name  = ly2mei

exec_dir  = bin
build_dir = build
doc_dir   = doc

dirs = $(exec_dir) $(build_dir) $(doc_dir)
units_in  = $(wildcard src/*.pas)
app_in 	  = $(wildcard app/*.lpr)

objects   = $(addprefix $(build_dir)/,$(notdir $(units_in:%.pas=%.o)))
app_out   = $(addprefix $(exec_dir)/,$(notdir $(basename $(app_in))))

doc_intro = $(wildcard *.txt)
doc_html  = $(addprefix $(doc_dir)/,$(doc_intro:%.txt=%.html) index.html)
doc_tex	  = $(build_dir)/$(app_name).tex
doc_pdf   = $(doc_dir)/$(app_name)-doc.pdf

src	  = $(app_in) $(units_in)
src_pdf	  = $(addsuffix .pdf,$(src))

full_pdf  = $(doc_dir)/$(app_name).pdf


FPCflagsTest = -vwhine -glh
FPCflagsDebug = $(FPCflagsTest) -dDEBUG
FPCflags = $(empty)
ifeq ($(TEST),1)
	FPCflags = $(FPCflagsTest)
endif
ifeq ($(DEBUG),1)
	FPCflags = $(FPCflagsDebug)
endif

.PHONY : all units docs pdfdoc view view-pdf clean 

all : $(app_out)

units : $(objects) 

docs : $(doc_html) 

pdfdoc : $(full_pdf)

$(dirs) :
	mkdir -p $(dirs)

$(exec_dir)/% : $(build_dir)/%
	cp -u $< $@

$(build_dir)/% : app/%.lpr $(objects) | $(dirs)
	fpc -FE$(build_dir) -Fu$(build_dir) $(FPCflags) $<

$(build_dir)/%.o : src/%.pas | $(dirs)
	fpc -FU$(build_dir) $(FPCflags) $<

$(doc_html) : $(doc_intro) $(units_in) | $(dirs) 
	pasdoc --output=$(doc_dir) --introduction=$(doc_intro) $(units_in)

$(doc_dir)/%-doc.pdf : $(build_dir)/%.pdf
	cp -u $< $@

$(build_dir)/%.pdf : $(build_dir)/%.tex
	latexmk -outdir=build -pdf $(basename $<)

$(full_pdf) : $(doc_pdf) $(src_pdf)
	pdfunite $(doc_pdf) $(src_pdf) $@
	rm $(src_pdf)

app/%.lpr.pdf : app/%.lpr
	code2pdf $<

src/%.pas.pdf : src/%.pas
	code2pdf $<

$(doc_tex) : $(doc_intro) $(units_in) | $(dirs)
	pasdoc --format latex --name=$(app_name) --output=$(build_dir) \
		--introduction=$(doc_intro) $(units_in)

view : $(doc_html)
	firefox $< &

view-pdf : $(full_pdf)
	atril $< &

clean :
	rm -rf $(dirs)

